-- เพิ่มเฉพาะตารางสถานะบอทบนฐานเดิมที่มี organizations/contacts แล้ว
BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS bot_chats (
    chat_id             TEXT PRIMARY KEY,
    chat_type           TEXT NOT NULL DEFAULT 'user'
                        CHECK (chat_type IN ('user', 'group', 'room')),
    subscribed_daily    BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bot_topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     TEXT NOT NULL REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    topic       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bot_topics_chat_id_topic_key UNIQUE (chat_id, topic)
);

CREATE INDEX IF NOT EXISTS bot_topics_chat_id_idx ON bot_topics(chat_id);

CREATE TABLE IF NOT EXISTS bot_settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS bot_chats_set_updated_at ON bot_chats;
CREATE TRIGGER bot_chats_set_updated_at
BEFORE UPDATE ON bot_chats
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS bot_settings_set_updated_at ON bot_settings;
CREATE TRIGGER bot_settings_set_updated_at
BEFORE UPDATE ON bot_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('bot_chats', 'bot_topics', 'bot_settings')
ORDER BY table_name;
