-- LINE News Bot: Contact database schema
-- Database: PostgreSQL
-- Compatible with Prisma models Organization and Contact
-- Run once on the new database. Safe to run again when the existing schema matches.

BEGIN;

-- Prisma enum: ContactRole
DO $$
BEGIN
    CREATE TYPE "ContactRole" AS ENUM ('PRIMARY', 'SECONDARY');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

-- Prisma enum: ContactType
DO $$
BEGIN
    CREATE TYPE "ContactType" AS ENUM (
        'GENERAL',
        'EMERGENCY',
        'MAINTENANCE',
        'IT_SUPPORT',
        'LAB_SUPPORT',
        'VENDOR',
        'OTHER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

-- Prisma model: Organization
CREATE TABLE IF NOT EXISTS organizations (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    code        TEXT UNIQUE,
    created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Prisma model: Contact
CREATE TABLE IF NOT EXISTS contacts (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     INTEGER NOT NULL,
    name                TEXT NOT NULL,
    phone               TEXT,
    email               TEXT,
    line_id             TEXT,
    position            TEXT,
    contact_role        "ContactRole" NOT NULL DEFAULT 'SECONDARY',
    contact_type        "ContactType" NOT NULL DEFAULT 'GENERAL',
    is_available_24h    BOOLEAN NOT NULL DEFAULT false,
    note                TEXT,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT contacts_organization_id_fkey
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Prisma @@index definitions
CREATE INDEX IF NOT EXISTS contacts_organization_id_idx
    ON contacts(organization_id);

CREATE INDEX IF NOT EXISTS contacts_contact_role_idx
    ON contacts(contact_role);

CREATE INDEX IF NOT EXISTS contacts_contact_type_idx
    ON contacts(contact_type);

-- Keep updated_at correct even when records are changed outside Prisma.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS organizations_set_updated_at ON organizations;
CREATE TRIGGER organizations_set_updated_at
BEFORE UPDATE ON organizations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS contacts_set_updated_at ON contacts;
CREATE TRIGGER contacts_set_updated_at
BEFORE UPDATE ON contacts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- สถานะแชทและการสมัครรับข่าวของ LINE bot (แทน storage.json)
CREATE TABLE IF NOT EXISTS bot_chats (
    chat_id             TEXT PRIMARY KEY,
    chat_type           TEXT NOT NULL DEFAULT 'user'
                        CHECK (chat_type IN ('user', 'group', 'room')),
    subscribed_daily    BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bot_topics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     TEXT NOT NULL REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    topic       TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bot_topics_chat_id_topic_key UNIQUE (chat_id, topic)
);

CREATE INDEX IF NOT EXISTS bot_topics_chat_id_idx ON bot_topics(chat_id);

CREATE TABLE IF NOT EXISTS bot_settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS bot_chats_set_updated_at ON bot_chats;
CREATE TRIGGER bot_chats_set_updated_at
BEFORE UPDATE ON bot_chats
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS bot_settings_set_updated_at ON bot_settings;
CREATE TRIGGER bot_settings_set_updated_at
BEFORE UPDATE ON bot_settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ความจำของคำสั่งถาม แยกตาม LINE chat_id
CREATE TABLE IF NOT EXISTS ai_conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     TEXT NOT NULL UNIQUE REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    provider    TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
    user_id             TEXT,
    role                TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content             TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ai_messages_conversation_id_id_idx
    ON ai_messages(conversation_id, id);

-- การบันทึกข้อความกลุ่มเป็น opt-in และปิดไว้โดยค่าเริ่มต้น
CREATE TABLE IF NOT EXISTS group_recording_settings (
    chat_id         TEXT PRIMARY KEY REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    enabled         BOOLEAN NOT NULL DEFAULT false,
    retention_days  INTEGER NOT NULL DEFAULT 30 CHECK (retention_days BETWEEN 1 AND 365),
    enabled_by      TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id         TEXT NOT NULL REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    user_id         TEXT,
    content         TEXT NOT NULL,
    line_message_id TEXT UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS group_messages_chat_id_created_at_idx
    ON group_messages(chat_id, created_at DESC);

DROP TRIGGER IF EXISTS ai_conversations_set_updated_at ON ai_conversations;
CREATE TRIGGER ai_conversations_set_updated_at
BEFORE UPDATE ON ai_conversations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS group_recording_settings_set_updated_at ON group_recording_settings;
CREATE TRIGGER group_recording_settings_set_updated_at
BEFORE UPDATE ON group_recording_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

-- Verification queries (read-only)
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'organizations', 'contacts', 'bot_chats', 'bot_topics', 'bot_settings',
      'ai_conversations', 'ai_messages', 'group_recording_settings', 'group_messages'
  )
ORDER BY table_name;

SELECT
    (SELECT COUNT(*) FROM organizations) AS organization_count,
    (SELECT COUNT(*) FROM contacts) AS contact_count,
    (SELECT COUNT(*) FROM bot_chats) AS bot_chat_count,
    (SELECT COUNT(*) FROM bot_topics) AS bot_topic_count,
    (SELECT COUNT(*) FROM bot_settings) AS bot_setting_count,
    (SELECT COUNT(*) FROM ai_conversations) AS ai_conversation_count,
    (SELECT COUNT(*) FROM ai_messages) AS ai_message_count,
    (SELECT COUNT(*) FROM group_messages) AS group_message_count;
