-- เพิ่มความจำ AI และระบบบันทึก/สรุปบทสนทนากลุ่ม
BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS ai_conversations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     TEXT NOT NULL UNIQUE REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    provider    TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
    user_id             TEXT,
    role                TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content             TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ai_messages_conversation_id_id_idx
    ON ai_messages(conversation_id, id);

CREATE TABLE IF NOT EXISTS group_recording_settings (
    chat_id         TEXT PRIMARY KEY REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    enabled         BOOLEAN NOT NULL DEFAULT false,
    retention_days  INTEGER NOT NULL DEFAULT 30 CHECK (retention_days BETWEEN 1 AND 365),
    enabled_by      TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id         TEXT NOT NULL REFERENCES bot_chats(chat_id) ON DELETE CASCADE,
    user_id         TEXT,
    content         TEXT NOT NULL,
    line_message_id TEXT UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS group_messages_chat_id_created_at_idx
    ON group_messages(chat_id, created_at DESC);

DROP TRIGGER IF EXISTS ai_conversations_set_updated_at ON ai_conversations;
CREATE TRIGGER ai_conversations_set_updated_at
BEFORE UPDATE ON ai_conversations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS group_recording_settings_set_updated_at ON group_recording_settings;
CREATE TRIGGER group_recording_settings_set_updated_at
BEFORE UPDATE ON group_recording_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'ai_conversations', 'ai_messages',
      'group_recording_settings', 'group_messages'
  )
ORDER BY table_name;
